site_name: django-admin-contexts
site_url: https://github.com/matagus/django-admin-contexts
repo_url: https://github.com/matagus/django-admin-contexts
theme:
  name: "material"
  palette:
    primary: blue
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.path
    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.follow
    - tables
nav:
  - Home: index.md
  - Contributing: contributing.md
  - License: license.md
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
