# Generated by Django 5.0.3 on 2024-03-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminContext",
            fields=[
                ("slug", models.CharField(max_length=100, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("models", models.ManyToManyField(to="contenttypes.contenttype")),
            ],
            options={
                "indexes": [models.Index(fields=["name"], name="django_admi_name_ba627c_idx")],
            },
        ),
    ]
